[package]
name = "rusttc_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttc_ast = { path = "../rusttc_ast" }
rusttc_lexer = { path = "../rusttc_lexer" }